### ISSUE TITLE
Usar testes e2e (Cypress) nos app-react-router

### ISSUE THREAD

**Issue by rafael-g-depaulo** [rafael-g-depaulo/ragic#10]
criar testes e2e usando Cypress para os 2 apps de teste

**Comment by LucasVinic** [comment]
Alterei a descrição da issue pra ser somente sobre testes no app-react-router, com a intenção de ter testes rodando na branch principal enquanto desenvolvemos a ragic-lib

**Comment by LucasVinic** [comment]
issue resolvida na branch tests/e2eTesting#10, e mergeada na main
